### Making houses dataframe

In [28]:
import pandas as pd
houses = pd.DataFrame()
houses['price'] = [53443, 39233, 29366, 43332023]
houses['bathroom'] = [2, 3, 4, 200]
houses['squarefeet'] = [1500, 2500, 1500, 40000]
houses

price  bathroom  squarefeet
0     53443         2        1500
1     39233         3        2500
2     29366         4        1500
3  43332023       200       40000

### Taking rows <20 from bathroom column

In [34]:
houses[houses['bathroom']<20]

price  bathroom  squarefeet  outlier
0  53443         2        1500        0
1  39233         3        2500        0
2  29366         4        1500        0

### Add outlier column and give 0s if bathroom <20 and 1s if false

In [30]:
import numpy as np
houses['outlier'] = np.where(houses['bathroom']<20,0,1)
houses

price  bathroom  squarefeet  outlier
0     53443         2        1500        0
1     39233         3        2500        0
2     29366         4        1500        0
3  43332023       200       40000        1

## Convert values in binary form and adding bins of array

In [31]:
from sklearn.preprocessing import Binarizer
age = np.array([[6],[12],[20],[36],[65]])
binarizer = Binarizer()
binarizer.fit_transform(age)
np.digitize(age,bins=[64])

array([[0],
       [0],
       [0],
       [0],
       [1]])

### Adding bins list

In [32]:
np.digitize(age,bins=[20, 30, 64])

array([[0],
       [0],
       [1],
       [2],
       [3]])

### If bins are at the point of values and right=True it considers to the right of the bin and if false than to the left of bin

In [33]:
x = np.array([1.2, 10.2, 12.4, 15.5])
bins = np.array([0, 5, 10.2, 15, 20])
np.digitize(x, bins, right = True)

array([1, 2, 3, 4])

### Taking new array and bin

In [35]:
arr = np.array([1.2, 2.4, 3.6, 3.8])
bins = np.array([1.0, 1.3, 2.5, 4.8, 10.0])
gfg = np.digitize(arr, bins)
gfg

array([1, 2, 3, 3])

### Working with multidimensional array and digitize

In [36]:
arr = np.array([[10.2, 21., 3.6, 14.0],[1.0, 5.0, 10.0, 15.0]])
bins = np.array([1.0, 1.3, 2.5,4.8,10.0])
gfg = np.digitize(arr,bins)
gfg

array([[5, 5, 3, 5],
       [1, 4, 5, 5]])

### Working with NaN

In [37]:
features = np.array([[1.1,11.1],[2.2,22.2],[3.3,33.3],[4.4,44.4],[np.NaN,55]])
features[~np.isnan(features).any(axis=1)]

array([[  1.1,  11.1],
       [  2.2,  22.2],
       [  3.3,  33.3],
       [  4.4,  44.4]])

### Adding array into dataframe with column names and drop NaN

In [27]:
dataframe = pd.DataFrame(features, columns=['feature1','feature2'])
dataframe.dropna()

feature1  feature2
0       1.1      11.1
1       2.2      22.2
2       3.3      33.3
3       4.4      44.4